version: '2'
services:
  spectralinkuserservice-mongodb:
    image: mongo:4.2.6
    ports:
      - '27017:27017'
    # volumes:
    #     - ~/volumes/jhipster/spectralinkUserService/mongodb/:/data/db/
